### ISSUE TITLE
Improve spanish providers

### ISSUE THREAD

**Issue by ashe2447** [streamflix-reborn/streamflix#4]
### Description

A lot of movies in the spanish providers are either in low quality (480-360) or don't work at all
Solo latino doesn't even work but when i go to the website (.net) it works perfectly 
In my case i try to watch star wars ep 3 but only 2 providers work but in 480p
 

### Provider

Cinecalidad, cine24h, cuevana2, cuevana3, sololatino, pelisplus

### Reproduction steps

1. Select any provider 
2. Select SW ep 3

### Operating system

Shield tv android 11

### Logs

```bash

```

### Please confirm the following

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] If related to a provider, I have checked the site and it works, but not the app.

**Comment by streamflix-reborn** [comment]
For Star Wars Episode 3, which provider should offer full HD? If it's Cinecalidad, full HD isn't available for streaming, but only for download.

**Comment by ashe2447** [comment]
Thought I think it should be cuevana3 and cuevan2. Those 2 were the only ones that worked before the latest update, though it was on 480p but at leats they worked and were compatible with the shield tv ai upscaling

**Comment by streamflix-reborn** [comment]
LaMovieRecomendado will be implemented in the next update but it is not full HD but the quality is slightly better than the others yes, regarding cuevana3 and cuevana2 which previously worked before the last update it is strange because they have not been touched, what error does it give?

**Comment by streamflix-reborn** [comment]
Netu there is no extractor but the file was deleted anyway

**Comment by streamflix-reborn** [comment]
Streamwish fixed in next release

**Comment by ashe2447** [comment]
> Streamwish fixed in next release

Fn goat 🐐

**Comment by ashe2447** [comment]
Post release 
The problem is still present and the movie is still capped at 480

**Comment by streamflix-reborn** [comment]
Per qualità i file su hlswish sembrano tutti rimossi

**Comment by streamflix-reborn** [comment]
For that series yes because the file is deleted on hlswish, moreover how The Matriarch works with the new update now

**Comment by ashe2447** [comment]
> For Calidad the files on hlswish seem to be all removed

Yeah it's probably a server problem and not an app problem so i prefer to leave it here, maybe check why some movies are compatible with the AI upscaler and others not in cinecalidad. And fix animefenix cus no server it's working and my goon sessions are in danger because of that

**Comment by streamflix-reborn** [comment]
Only a few extractors are missing and at least one server should work if it still has the file

**Comment by ashe2447** [comment]
> For Animefenix, what series are you trying out?

Overflow

![Image](https://github.com/user-attachments/assets/bb7e97a0-fe50-4951-8592-47827b65f99a)

**Comment by streamflix-reborn** [comment]
ok yes the extractors are missing for this series

**Comment by streamflix-reborn** [comment]
I'll see which one can be added among those who still have the file

**Comment by ashe2447** [comment]
Sorry to bother again with this, can we get a fix on the Sololatino provider? There's lot's of media that can't be played but when i go to the .net it works fine. I even tried watching the SW Clone Wars 2008 tv show and it was capable of full HD stream, something that no other sp provider could do for this specific case
I would love to see this provider get some love

**Comment by ashe2447** [comment]
After testing again with the update it seems there's a problem with this specific tv shows because i even tried watchin ep3(which didn't worked bef at all) and now it works even at 1080p 
On the clone wars show it says "no servers found"
Great improvements though, thank you

**Comment by ashe2447** [comment]
Update: now the servers not found message is appearing in all movies and tv shows i try to watch, i was in the middle of watching peacemaker and suddenly the message appeared and from then i couldn't see anything

**Comment by streamflix-reborn** [comment]
Some movies and TV series still need a further fix

**Comment by streamflix-reborn** [comment]
For clone wars last night I managed to solve it and wanted to release the update today but with this Peacemaker series there is still more to do

**Comment by streamflix-reborn** [comment]
Yesterday they must have seen the fix I made and changed it because it's different on almost everything.

**Comment by ashe2447** [comment]
> Yesterday they must have seen the fix I made and changed it because in fact almost everything is different today

They?? You mean the people behind the provider???

**Comment by streamflix-reborn** [comment]
> > Yesterday they must have seen the fix I made and changed it because in fact almost everything is different today
> 
> They?? You mean the people behind the provider???

Yes

**Comment by ashe2447** [comment]
> > > Yesterday they must have seen the fix I made and changed it because in fact almost everything is different today
> > 
> > 
> > They?? You mean the people behind the provider???
> 
> Yes

Wow so the devs are sabotaging your job. Interesting 

Great job though the tv show is working now and if everything else works fine I'll close this issue

**Comment by ashe2447** [comment]
> Try a little if it works

Just tried it in my phone and shield and the clone wars show is working on all seasons and in 1080p, also all the other movies and shows are working fine 
🐐🐐🐐🐐
